services:
  app:
    build: docker/php
    volumes:
      - ./:/app
    networks:
      - project-network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    networks:
      - project-network
    depends_on:
      - app

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: yii2user
      POSTGRES_PASSWORD: yii2pass
      POSTGRES_DB: yii2db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project-network

volumes:
  postgres_data:

networks:
  project-network:
    driver: bridge